import type { Metadata } from "next";
import NavMenu from '@/app/NavMenu';
import "./globals.css";
import AuthProvider from "./AuthProvider";
import Link from 'next/link';
import { Open_Sans } from 'next/font/google';

const myFont = Open_Sans({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({
  children}: Props) {
  return (
    
    <AuthProvider>
    
    <html lang="en">
    <body className={myFont.className}>
    <div className="container">
      <NavMenu/>
      <main>{children}</main>
    
    </div>
    </body>
    </html>
    </AuthProvider>
    
  );
}
